# Generated by Django 3.0.8 on 2020-07-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.CharField(default='none', max_length=300),
            preserve_default=False,
        ),
    ]
